version: '3.8'

services:
  astro-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
      - PORT=4321
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4321/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  astro-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    profiles:
      - dev
